In [1]:
# 43 Numpy
'''
NumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, 
# constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices.

http://numpy.org

'''

'\nNumPy es una extensión de Python, que le agrega mayor soporte para vectores y matrices, \n# constituyendo una biblioteca de funciones matemáticas de alto nivel para operar con esos vectores o matrices.\n\nhttp://numpy.org\n\n'

In [2]:
# Necesitamos importarlo.
# para que sea comodo le voy a asignar el alias de np
import numpy as np

In [3]:
# tiene un monton de métodos
# https://numpy.org/doc

print(np.zeros(4))
print(np.ones(5))
print(np.arange(2,20,3))

[0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[ 2  5  8 11 14 17]


In [4]:
# Con numpy podemos hacer arrays de listas

l1 = [1,2,3,4]
l2 = [34,56,2,7]
l3 = [3.14,14,15,92]

l_multi = (l1,l2,l3)
array = np.array(l_multi)

array

array([[ 1.  ,  2.  ,  3.  ,  4.  ],
       [34.  , 56.  ,  2.  ,  7.  ],
       [ 3.14, 14.  , 15.  , 92.  ]])

In [5]:
# Operaciones con arrays (+,-,*,/,**)
# hay que tener en cuenta que las operaciones no modifican el array

print(array * 2)

array

[[  2.     4.     6.     8.  ]
 [ 68.   112.     4.    14.  ]
 [  6.28  28.    30.   184.  ]]


array([[ 1.  ,  2.  ,  3.  ,  4.  ],
       [34.  , 56.  ,  2.  ,  7.  ],
       [ 3.14, 14.  , 15.  , 92.  ]])

In [6]:
# para eso tendremos que hacerlo como normalmente
array = array - 3.14
array

array([[-2.14, -1.14, -0.14,  0.86],
       [30.86, 52.86, -1.14,  3.86],
       [ 0.  , 10.86, 11.86, 88.86]])

In [7]:
# Podemos ver el tipo y estructura del array

print(array.dtype)
print(array.shape)
array

float64
(3, 4)


array([[-2.14, -1.14, -0.14,  0.86],
       [30.86, 52.86, -1.14,  3.86],
       [ 0.  , 10.86, 11.86, 88.86]])

In [8]:
# Podemos indexar el array como ya conocemos

a1 = np.arange(11)

print(a1)

a1[3:7]

[ 0  1  2  3  4  5  6  7  8  9 10]


array([3, 4, 5, 6])

In [9]:
a2 = np.array(([1,2,3],[4,5,6],[7,8,9]))

print(a2)

a2[1][1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5

In [10]:
# con numpy es muy sencillo hacer matrices transpuestas

a1 = np.arange(15).reshape((3,5))
print(a1)

a2 = a1.T
a2


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [11]:
# entrada y salida de arrays
# podemos guardarlos y cargarlos como ficheros numpy

a1 = np.arange(6)
np.save('a1S', a1)
np.load('a1S.npy')

array([0, 1, 2, 3, 4, 5])

In [12]:
a2 = np.arange(8)
np.savez('arrays',x=a1,y=a2)
arrays = np.load('arrays.npz')
arrays['x']

array([0, 1, 2, 3, 4, 5])

In [13]:
# o como txt, en este caso indicamos con la , donde se hace la división del array

np.savetxt('arrays.txt',a2,delimiter=',')
np.loadtxt('arrays.txt',delimiter=',')

array([0., 1., 2., 3., 4., 5., 6., 7.])

In [14]:
# ejemplos de Funciones con arrays
a1 = np.arange(5)
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [15]:
np.random.rand(5)

array([0.52098243, 0.7587436 , 0.29114175, 0.46587326, 0.71572657])

In [16]:
a1 = np.arange(5)
l1 = [5,6,1,2,0]
a2 = np.array(l1)

np.add(a1,a2)
np.maximum(a1,a2)

[0 1 2 3 4]
[5 6 1 2 0]


array([5, 6, 2, 3, 4])